name: python autotests ui

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: all
        options:
          - smoke
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run ui tests
    steps:
    - name: Checkout autests
      uses: actions/checkout@v6
    - name: Set up Python environment
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies.
      run: pip install -r requirements.txt
    - name: run all tests
      if: "github.event.inputs.deployment_target=='all'"
      run: pytest --alluredir=allure-results
    - name: run smoke tests
      if: "github.event.inputs.deployment_target=='smoke'"
      run: pytest -m smoke --alluredir=allure-results
    - name: Install Java
      uses: actions/setup-java@v5
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Install Allure
      run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.41.0/allure-2.41.0.tgz && sudo tar -zxvf allure-2.41.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.41.0/bin/allure /usr/bin/allure
    - name: Generate report
      run: allure generate -c allure-results -o allure-report
    - name: Save allure report
      uses: actions/upload-artifact@v7
      with:
        name: allure-report
        path: allure-report
        retention-days: 1
      
        
