name: python autotests ui

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: all
        options:
          - smoke
          - regretion
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run ui tests
    steps:
    - name: Checkout autests
      uses: actions/checkout@v6
    - name: Set up Python environment
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies.
      run: pip install -r requirements.txt
    - name: run tests
      run: pytest
      
        
